"""PowerShell script generation for automated Windows optimization actions."""

from __future__ import annotations

from src.config.settings import ULTIMATE_PERFORMANCE_GUID

_PRELUDE = r'''
# Generated by Windows Automation Toolkit.
$ErrorActionPreference = "Continue"

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "== $Message ==" -ForegroundColor Cyan
}

function Set-RegistryDword {
    param(
        [string]$Path,
        [string]$Name,
        [int]$Value
    )
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -Path $Path -Force | Out-Null
    }
    New-ItemProperty -Path $Path -Name $Name -Value $Value -PropertyType DWord -Force | Out-Null
}

function Set-RegistryString {
    param(
        [string]$Path,
        [string]$Name,
        [string]$Value
    )
    if (-not (Test-Path -LiteralPath $Path)) {
        New-Item -Path $Path -Force | Out-Null
    }
    New-ItemProperty -Path $Path -Name $Name -Value $Value -PropertyType String -Force | Out-Null
}

function Remove-ContentsIfPresent {
    param([string[]]$Paths)
    foreach ($Path in $Paths) {
        $ExpandedPath = [Environment]::ExpandEnvironmentVariables($Path)
        if (Test-Path -LiteralPath $ExpandedPath) {
            Write-Host "Cleaning $ExpandedPath"
            Get-ChildItem -LiteralPath $ExpandedPath -Force -ErrorAction SilentlyContinue |
                Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}

function Disable-ServiceIfPresent {
    param([string[]]$Names)
    foreach ($Name in $Names) {
        $Service = Get-Service -Name $Name -ErrorAction SilentlyContinue
        if ($Service) {
            Write-Host "Disabling service $Name"
            Stop-Service -Name $Name -Force -ErrorAction SilentlyContinue
            Set-Service -Name $Name -StartupType Disabled -ErrorAction SilentlyContinue
        }
    }
}

$Principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $Principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Warning "Run this action as Administrator so every optimization can be applied."
}
'''

_FOOTER = r'''
Write-Step "Optimization complete"
Write-Host "Restart Windows to let all service, registry, and power changes take effect."
'''


def optimization_script_blocks() -> dict[str, str]:
    """Return the named PowerShell blocks a optimization action can select."""
    return {
        "restore_point": r'''
Write-Step "Create restore point"
try {
    Enable-ComputerRestore -Drive "$env:SystemDrive\" -ErrorAction SilentlyContinue
    Checkpoint-Computer -Description "Before Windows Automation Toolkit optimization" -RestorePointType "MODIFY_SETTINGS" -ErrorAction Stop
} catch {
    Write-Warning "Restore point could not be created: $($_.Exception.Message)"
}
'''.strip(),
        "cleanup": r'''
Write-Step "Disk cleanup"
Stop-Service -Name wuauserv,bits -Force -ErrorAction SilentlyContinue
Remove-ContentsIfPresent @(
    "%TEMP%",
    "$env:WINDIR\Temp",
    "$env:WINDIR\Prefetch",
    "$env:WINDIR\SoftwareDistribution\Download",
    "$env:ProgramData\NVIDIA Corporation\Downloader",
    "$env:ProgramFiles\NVIDIA Corporation\Installer2"
)
Start-Service -Name wuauserv,bits -ErrorAction SilentlyContinue
Start-Process -FilePath "wsreset.exe" -WindowStyle Hidden -Wait -ErrorAction SilentlyContinue
'''.strip(),
        "network": r'''
Write-Step "Network throughput and adapter power saving"
netsh int tcp set global autotuninglevel=disabled
netsh int tcp set supplemental template=internet congestionprovider=ctcp
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\Psched" "NonBestEffortLimit" 0

$AdapterTweaks = @(
    "Energy Efficient Ethernet",
    "Energy Efficient Ethernet (EEE)",
    "Advanced EEE",
    "Gigabit Lite",
    "Green Ethernet",
    "Power Saving Mode",
    "Selective Suspend"
)
foreach ($Adapter in Get-NetAdapter -Physical -ErrorAction SilentlyContinue) {
    foreach ($DisplayName in $AdapterTweaks) {
        Set-NetAdapterAdvancedProperty -Name $Adapter.Name -DisplayName $DisplayName -DisplayValue "Disabled" -NoRestart -ErrorAction SilentlyContinue
    }

    $PowerCommand = Get-Command Set-NetAdapterPowerManagement -ErrorAction SilentlyContinue
    if ($PowerCommand) {
        $PowerParams = @{ Name = $Adapter.Name; ErrorAction = "SilentlyContinue" }
        foreach ($ParamName in @("AllowComputerToTurnOffDevice", "DeviceSleepOnDisconnect", "WakeOnMagicPacket", "WakeOnPattern", "SelectiveSuspend")) {
            if ($PowerCommand.Parameters.Keys -contains $ParamName) {
                $PowerParams[$ParamName] = "Disabled"
            }
        }
        Set-NetAdapterPowerManagement @PowerParams
    }
}
'''.strip(),
        "performance": rf'''
Write-Step "Power, gaming, storage, and peripheral performance"
$UltimateGuid = "{ULTIMATE_PERFORMANCE_GUID}"
$DuplicateOutput = powercfg -duplicatescheme $UltimateGuid 2>&1
$CreatedGuid = [regex]::Match(($DuplicateOutput | Out-String), "[0-9a-fA-F]{{8}}-[0-9a-fA-F]{{4}}-[0-9a-fA-F]{{4}}-[0-9a-fA-F]{{4}}-[0-9a-fA-F]{{12}}").Value
if ($CreatedGuid) {{
    powercfg -setactive $CreatedGuid
}} else {{
    powercfg -setactive "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
}}
powercfg /hibernate off

Set-RegistryDword "HKLM:\SYSTEM\CurrentControlSet\Control\GraphicsDrivers" "HwSchMode" 2
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\StorageSense\Parameters\StoragePolicy" "01" 0
Set-RegistryDword "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server" "fDenyTSConnections" 1
Set-RegistryDword "HKCU:\Software\Microsoft\Clipboard" "EnableClipboardHistory" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Clipboard" "CloudClipboardAutomaticUpload" 0
Set-RegistryDword "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config" "DODownloadMode" 0
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization" "DODownloadMode" 0

Set-RegistryDword "HKCU:\System\GameConfigStore" "GameDVR_Enabled" 0
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\GameDVR" "AllowGameDVR" 0
Set-RegistryDword "HKCU:\Software\Microsoft\GameBar" "AllowAutoGameMode" 1
Set-RegistryDword "HKCU:\Software\Microsoft\GameBar" "AutoGameModeEnabled" 1
Set-RegistryDword "HKCU:\Software\Microsoft\GameBar" "ShowStartupPanel" 0
Set-RegistryDword "HKCU:\Software\Microsoft\GameBar" "GameMode" 1

Set-RegistryString "HKCU:\Control Panel\Mouse" "MouseSpeed" "0"
Set-RegistryString "HKCU:\Control Panel\Mouse" "MouseThreshold1" "0"
Set-RegistryString "HKCU:\Control Panel\Mouse" "MouseThreshold2" "0"
Set-RegistryString "HKCU:\Control Panel\Mouse" "DoubleClickSpeed" "200"
Set-RegistryString "HKCU:\Control Panel\Accessibility\StickyKeys" "Flags" "506"
Set-RegistryString "HKCU:\Control Panel\Accessibility\Keyboard Response" "Flags" "122"
Set-RegistryString "HKCU:\Control Panel\Accessibility\ToggleKeys" "Flags" "58"
'''.strip(),
        "privacy": r'''
Write-Step "Privacy, telemetry, activity, and app permissions"
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo" "Enabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy" "TailoredExperiencesWithDiagnosticDataEnabled" 0
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" "AllowTelemetry" 1
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" "DisableTailoredExperiencesWithDiagnosticData" 1
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" "PublishUserActivities" 0
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" "UploadUserActivities" 0
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors" "DisableLocation" 1
Set-RegistryString "HKCU:\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location" "Value" "Deny"
Set-RegistryDword "HKCU:\Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy" "HasAccepted" 0
Set-RegistryDword "HKCU:\Software\Microsoft\InputPersonalization" "RestrictImplicitTextCollection" 1
Set-RegistryDword "HKCU:\Software\Microsoft\InputPersonalization" "RestrictImplicitInkCollection" 1
Set-RegistryDword "HKCU:\Software\Microsoft\InputPersonalization\TrainedDataStore" "HarvestContacts" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications" "GlobalUserDisabled" 1

foreach ($Permission in @("webcam", "microphone", "location", "appDiagnostics", "userNotificationListener", "contacts", "appointments", "phoneCall", "radios", "bluetoothSync")) {
    Set-RegistryString "HKCU:\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\$Permission" "Value" "Deny"
}
'''.strip(),
        "interface": r'''
Write-Step "Explorer, Start, taskbar, tips, suggestions, and accessibility launchers"
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "LaunchTo" 1
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer" "ShowRecent" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer" "ShowFrequent" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "Start_TrackProgs" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "Start_TrackDocs" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "Start_ShowRecentlyAddedApps" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Search" "SearchboxTaskbarMode" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "ShowTaskViewButton" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" "NoInstrumentation" 1

Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "ContentDeliveryAllowed" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "FeatureManagementEnabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "OemPreInstalledAppsEnabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "PreInstalledAppsEnabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "SilentInstalledAppsEnabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "SoftLandingEnabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "SubscribedContent-338388Enabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "SubscribedContent-338389Enabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "SubscribedContent-353698Enabled" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" "SystemPaneSuggestionsEnabled" 0
Set-RegistryDword "HKLM:\SOFTWARE\Policies\Microsoft\Windows\CloudContent" "DisableWindowsConsumerFeatures" 1

Set-RegistryDword "HKCU:\Software\Microsoft\ScreenMagnifier" "RunningState" 0
Set-RegistryDword "HKCU:\Software\Microsoft\Narrator\NoRoam" "WinEnterLaunchEnabled" 0
Remove-Item "$env:APPDATA\Microsoft\Windows\Recent\*" -Recurse -Force -ErrorAction SilentlyContinue
Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue
Start-Process explorer.exe
'''.strip(),
        "services": r'''
Write-Step "Optional service optimization"
Disable-ServiceIfPresent @(
    "HvHost",
    "vmms",
    "vmicheartbeat",
    "vmickvpexchange",
    "vmicshutdown",
    "vmictimesync",
    "vmicvmsession",
    "vmicrdv",
    "SensorService",
    "SensorDataService",
    "SensrSvc",
    "WbioSrvc",
    "XboxNetApiSvc",
    "XboxGipSvc",
    "XblAuthManager",
    "XblGameSave",
    "DiagTrack",
    "MixedRealityOpenXRSvc",
    "WalletService",
    "SEMgrSvc",
    "lmhosts",
    "SCPolicySvc",
    "RetailDemo",
    "TapiSrv",
    "BDESVC",
    "AxInstSV",
    "TabletInputService",
    "WSearch",
    "SysMain",
    "Fax",
    "MapsBroker"
)
'''.strip(),
    }


def build_optimization_script(groups: list[str]) -> str:
    """Build the PowerShell script for a set of optimization groups."""
    blocks = optimization_script_blocks()
    selected_blocks = [blocks[group] for group in groups if group in blocks]
    return "\n".join([_PRELUDE.strip(), *selected_blocks, _FOOTER.strip(), ""])
